/**
 * Generated by `pnpm db:types` — DO NOT EDIT BY HAND.
 *
 * This is the shape the Supabase generator emits for an empty `public` schema.
 * It is a placeholder until migration 0001 lands (Task 1.3), at which point
 * `pnpm db:types` overwrites this file with the real schema types.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: { [_ in never]: never };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};
